### ISSUE TITLE
Multi color multi line textbox

### ISSUE THREAD

**Issue by kbilsted** [TomaszRewak/C-sharp-console-multiplexer#11]
A feature idea. Change the color or background color based on some rules. 

E.g. first char on the line is simple rule that governs colouring git diffs

**Comment by jzabroski** [comment]
Great idea

**Comment by TomaszRewak** [comment]
Indeed, sounds like a good idea.
Though I wonder what might be the best design for this.
I think that those rules shouldn't be contextual as controls don't persist their states. It might invite some nasty performance bottlenecks. If one would want to, for example, highlight a specific word in a sentence with a different color, I would recommend to use a vertical stack panel with separate text boxes of different colors nested within it.
I also don't think this should be limited to text boxes only, as currently the multi line text box is actually not a textbox, but a text box wrapped in a wrap panel.

So my idea is as follows:
Let's create an `abstract` pass-through control (`Decorator`?) that behaves similarly to the `SimpleControl`, but on each call to the `operator[]` allows the inheriting class to modify the character (including front and back color) received from the child component. A user implementation would look something like this:
```csharp
internal class MyDecorator : Decorator
{
  public override Character Decorate(in Character character, in Position position)
  {
    return position.X == 0
      ? character.WithBackground(...)
      : character;
  }
}
...
var myDecorator = new MyDecorator
{
  Content = ...
}
```
How does it sound?

**Comment by kbilsted** [comment]
Hi @TomaszRewak  thanks for the quick reply.

I've tried your library too little to really understand your proposed solution. I'm not sure I fully understand the `position`. Given I may have a wrapping textboxt and the textboxt may be inside a (schroll?)panel etc. how do I know `0` is the first character? If that always be the case, then why not have an `int` for position?

A different albeit less general idea, would be to allow some structured input other than text, similar to markup where you can then annotate directly the colouring.

Why are you using the `in` operator in the example. Haven't seen it is use for quite a while.

Finally, when being able to control the colors, it is equally important to be able to control the cursor color otherwise you run into problems like the bug in another gui library https://github.com/migueldeicaza/gui.cs/issues/308

**Comment by TomaszRewak** [comment]
The `position` is always relative to the control itself. So if you use a `WrapPanel`, the third character in the second row will always have a position of `{x: 2, y: 1}`, no matter where on the screen that `WrapPanel` is placed, if it's stored in a `ScrollPanel` and what is its content.
You cannot simply retrieve the original position of the nested control as long as that control is not setting the `MouseListener` property of the `Cell` (what should only be done by controls that actually want to listen to mouse events).
The position in the example above is simply a position within the `Decorator` control.
But just to be sure, because I don't know if I understood the proposal correctly: is it about custom formatting of text blocks (editable) or text blocks (not editable) controls? The `Decorator` would work on both, but, as mentioned before, no markup formatting rules would be supported.
When it comes to custom-formatted rule-based multi-line editors it's quite tricky to get them right so that they would be both easy to use and flexible enough. That's probably why we don't have anything like that in the native HTML-CSS.
If I were to implement it here, I would probably go for a new (single line) `TextBox` control that would have a regex based rules. If needed, it could be wrapped in a `WrapPanel` to get a multi-line text box (but with no support for forcing a new line). 
(Btw. maybe adding a proper multi-line text box with new line insertion might be a good idea).
So, yeah, it's tricky :D 
Probably the simplest and most flexible way of achieving the same result in case of non-editable text blocks is to manually split the text into separately formatted parts. Actually that's how I'm handling it in my other project where I do it for an editable multi-line text box with rule-based formatting (so probably exactly what you are looking for, but in HTML/CSS/JS): https://github.com/TomaszRewak/TimeWriter

When it comes to the `in` parameter, it's actually not needed in the case of the `Position`, but might improve the performance a little bit in the case of `Character` as it's quite a bulky `struct`.
When it comes to the cursor color, it's currently managed by the control displaying it, and not the host framework. It can set it to whatever color the text box wants it to be, based on it's internal color (though currently it's not adjustable in the standard `TextBox` - I should change that). The host control can overwrite this color, so you should be careful when applying custom formatting around the `TextBox` control.

**Comment by kbilsted** [comment]
My current needs are multiline editable textboxes where coloring is decided on the first 1-3 characters pr line.

A bonus would be coloring columns in a multicolumn listview.

All this is needed for a small open source app that I hope to get around to making. I've started using another console gui framework - but it turned out too buggy and the author was not pulling even the simplest bugfix PRs.

Any help with structuring the app would be great - like the overall forms and how they should interact. I can flesh out some example screens in more details if you feel inclined to help out. I've read the documentation and how you don't want to make a Form class.

**Comment by TomaszRewak** [comment]
> coloring is decided on the first 1-3 characters pr line.

So it seems that the `Decorator` might indeed satisfy this requirement.

> A bonus would be coloring columns in a multicolumn listview.

The `DataGrid` should be a perfect match.

The main problem I see is that this framework currently doesn't have a multi-line editor control. You can wrap a single line editor, but the `\n` character will not break the line and up/down arrows will not work for navigation. I will have to think on how to incorporate it into the current design, but it's definitely a nice control to have.

I will try to work on the design of it tomorrow.

**Comment by TomaszRewak** [comment]
Added `Decorator` in fdfa9020c32dc61aff88e3dbf63273b8d5f385f3.

**Comment by kbilsted** [comment]
Looked briefly at your example. closing this for now

**Comment by TomaszRewak** [comment]
Reopening, as I still want to implement the multi-line text box.

**Comment by jzabroski** [comment]
It would be pretty awesome to use DiffPlex with a multi-line multi-color text box!

**Comment by TomaszRewak** [comment]
When it comes to controls like this, I would say that users would have to define them themselves, based on their actual needs :P 
As those are very specific and hard to get right in a generic design.
But I definitely want to create something that works as a simple multi-line text box.

**Comment by TomaszRewak** [comment]
OK, I've added the `BreakPanel` control that works similarly to the `WrapPanel`, but breaks the line also on the new line character. That should satisfy both multi-line text block and text boxes. I will also allow to tup a `Decorator` between itself and the `TextBox` to achieve some context aware color formatting.

**Comment by kbilsted** [comment]
@jzabroski  you can write a diff'er in 20 lines of code, See https://github.com/kbilsted/KBGit/blob/master/Git.cs#L618
