### ISSUE TITLE
correct formatting?

### ISSUE THREAD

**Issue by kbilsted** [TomaszRewak/C-sharp-console-multiplexer#13]
Just learning the framework. Is this as expected?

    class Program
    {
        static void Main(string[] args)
        {
            ConsoleManager.Setup();
            ConsoleManager.Resize(new Size(150, 40));
            ConsoleManager.Content =
                new Box()
                {
                    Content = new Border()
                    {
                        Content =
                            new HorizontalStackPanel()
                            {
                                Children = new[] { new TextBlock { Text = "Hello world" }, new TextBlock { Text = "22Hello world22" }, }
                            }
                    }
                };

            Console.ReadKey();
        }
    }

![image](https://user-images.githubusercontent.com/1616338/70260903-97a39b80-1791-11ea-9b60-23c7939ef4de.png)

**Comment by TomaszRewak** [comment]
Discussion in #14

**Comment by kbilsted** [comment]
why is this closed? it is clearly not showing any text `"Hello world"` or `"22Hello world22"`   #14 is unrelated IMHO

**Comment by TomaszRewak** [comment]
Reopened.
The format here is incorrect.

The `HorizontalStackPanel` will always:
- adjust its width to the width of its content,
- take up the entire available space vertically.

That's by design, because some child components might rely on the size of the container when calculating their size and trying to adjust both based on each other might lead to an infinite looping.
The `Box` by default centers content both vertically and horizontally. When in this mode, it tells its child components that they have infinite available space in both directions.
And so the `HorizontalStackPanel` will have an infinite height in this configuration (even if there is a `Border` in between).
If you want to achieve desired result, you have to restrict the height of the `HorizontalStackPanel` manually using a `Boundry` (either around the `HorizontalStackPanel` with `MaxHeight` set to `1` or around the border with `MaxHeight` set to `3` - to include the border).

```csharp
static void Main(string[] args)
{
	ConsoleManager.Setup();
	ConsoleManager.Resize(new Size(150, 40));
	ConsoleManager.Content = new Box()
	{
		Content = new Boundary()
		{
			MaxHeight = 3,
			Content = new Border()
			{
				Content = new HorizontalStackPanel()
				{
					Children = new[] { new TextBlock { Text = "Hello world" }, new TextBlock { Text = "22Hello world22" }, }
				}
			}
		}
	};

	Console.ReadKey();
}
```

**Comment by TomaszRewak** [comment]
![image](https://user-images.githubusercontent.com/5797540/70263101-e2bfad80-1795-11ea-9560-5f2bd66bce23.png)

**Comment by kbilsted** [comment]
> The HorizontalStackPanel will always:
> 
>     adjust its width to the width of its content,
>     take up the entire available space vertically

should this go into the documentation?

From reading the code, I would think I got a border taking up all the space of the console as displayed in #14. Perhaps the infinite should be limited to the size of the console? But I guess that is problematic when you use components with scrollbars.

if you don't think the example shows a buggy UI then close this issue.

**Comment by TomaszRewak** [comment]
Theoretically the size of the `Box` `Content` could be limited to the `Size` of this container.
But there are two problems with this solution:
- After specifying the vertical alignement to `Center`, the horizontal stack panel still wouldn't be centered (it would just take the entire height), so the final outcome could still be considered as undesirable
- If the child would want to display more content then the size of the container, it would end up being align to the left-top (and cutting the content on the right-bottom) rather then being aligned to the center (and cutting the content on all sides equally)

Also, if one would want to fill all of the available vertical/horizontal space while centering the item in the other axis, the `VerticalContentPlacement` or the `HorizontalContentPlacement` should be simply set to `Stretch`, which strictly defines this behavior.
