### ISSUE TITLE
Not working example

### ISSUE THREAD

**Issue by Krzysztof-Kozaczuk** [TomaszRewak/C-sharp-console-multiplexer#21]
After download zip file and run example there only works Key UP/DOWN on Popup.
Example not reacts on mouse  when i want  e.g change tabs

**Comment by TomaszRewak** [comment]
The main example (the one with the chess board) is keyboard-only.
That's because mouse handling is system specific and is not the main focus of this library.

But in the project called `ConsoleGUI.MouseExample` you can find a Windows specific example that introduces a `MouseHandler` class which provides support for mouse event processing.
