### ISSUE TITLE
DataGrid pages

### ISSUE THREAD

**Issue by Paffo** [TomaszRewak/C-sharp-console-multiplexer#25]
Hi,
would it be possible to have side page scrolling for the DataGrid?
Let's say the DataGrid contains more items than the console can contain for it's size, it could display only a determinate amount of them and allow page navigation with left and right arrows, cycling through the items.
My current solution for this is having custom input on the tab the DataGrid is in, and 2 Arrays, one as "all items" and one as the DataGrid source. On arrow press, i update the DataGrid source array with the range of items needed, it works fine but can you perhaps suggest of a better way?

Please tell me if I'm missing something, I am aware of the endless vertical panel, but i need not to lose track of how many items are behind.

Thanks

**Comment by TomaszRewak** [comment]
Hey,
Hmm, I think your current solution of updating the source is indeed the best. I don't think using the `VerticalStackPanel`/`VerticalScrollPanel` would be a good idea here, as that would mean that the header would go out of the view when scrolling down.
Your current solution also gives you a flexibility of defining any scrolling behavior you prefer (scrolling the entire page down vs. scrolling down item by item).
So I think I would just stick with it - that's indeed the way I would recommend for approaching this problem.

**Comment by Paffo** [comment]
Hi,
it's technically unrelated to the issue itself, but i cant quite understand how input handling works.
What i mean is that assigning data to variables fires on the program start not on the keypress, so i dont quite understand how to assign the same key to different controls and doing a different action based on data currently available.
What i wanted was to update the sourceitem of both Datagrids i have on the press of the right key, but it would fire on both datagrids ignoring which one was focused (they are in different TabPanels.
My solution for this was to edit the TabPanel adding a method the returns the current tab ID and then checked against it, but im wondering if there's a better way.
Also i was wondering if there's any way to speedup the writing process of the console.
Overall very nice framework, MUCH easier to use than terminal.gui.cs, wonderful job.

**Comment by TomaszRewak** [comment]
Thanks! :)
That's actually the intended way of handling input. Structurally it would probably look like this:
```
	internal sealed class DataGridInputController : IInputListener
	{
		private readonly DataGrid<Row> _dataGrid;
		private readonly List<Row> _dataSource;

		// ...

		public void OnInput(InputEvent inputEvent)
		{
			if (inputEvent.Key.Key == ConsoleKey.LeftArrow)
			{
				_dataGrid.Data = // _dataSource.Skip(...).Take(...)...
				inputEvent.Handled = true;
			}
			// ...
		}
	}

	internal sealed class ApplicationInputController : IInputListener
	{
		private readonly TabPanel _tabPanel;
		private readonly DataGridInputController _tabOneDataGridInputController;
		private readonly DataGridInputController _tabTwoDataGridInputController;

		// ...

		public void OnInput(InputEvent inputEvent)
		{
			switch(_tabPanel.CurrentTab)
			{
				case 0:
					_tabOneDataGridInputController.OnInput(inputEvent);
					break;
				case 1:
					_tabTwoDataGridInputController.OnInput(inputEvent);
					break;
			}
		}
	}
```
And then in your main program loop you would just call the `ConsoleManager.ReadInput(_listOfYourInputContollers);`.

It works this way mostly because there is no concept of control focusing in this framework - and so the program using it has to decide on its own which controls should process the input. That's mostly because the console UIs, unlike standard GUI apps, mainly do not support mouse. And if one would put two scroll panels into the same view, were both would be visible, there would be no good and generic enough way to determine which one of them should actually be reacting to the user input. That's why I went with a simpler design, where the framework only provides a simple interface for listening to input events, but the rest is up to the app itself.

What console are you using? The speed of rendering is greatly dependent on the terminal itself.  The framework attempts to optimize it a bit (for example by not rendering cells that did not change), but it's still rendering everything character by character - which might not be optimal for all terminals.

**Comment by Paffo** [comment]
Currently using the standard windows CMD, which alternative would you suggest?
By the way, how would you proceed if you had to implement a CheckBox?
I need to be able to toggle specific functions on and off, i can technically assign an hotkey to them, but i would prefer some visual confirmation (changing background color of a TextBlock might do as well, but im open to suggestions).

**Comment by TomaszRewak** [comment]
I would highly recommend switching to Windows Terminal. When using it you can still choose which shell you want to run, so it's possible to use CMD from there as well. But I would also recommend moving to PowerShell. One advantage of using those two from the perspective of this framework is that they support the "true color formatting" - so a full RGB color pallet. But of course they are much better in many different aspects as well. The CMD is quite old and is maintained mostly because of legacy reasons :P

When it comes to the combo box implementation I would probably either display something like this:
```
[ ] Option a [F1]
[x] Option b [F2]
[x] Option c [F3]
```
And use the `F1`, `F2` and `F3` keys to toggle them.
Or something like this:
```
 [ ] Option a
→[x] Option b
 [x] Option c
```
Where the user would `Tab` through different options (where the current one would be either highlighted with some color or some other indicator) and the toggling would be done with the spacebar (that's how it works in regular window GUIs).
Of course you can also go creative with how you want to display the `[x]` - for example by using unicode checkboxes (`☑` and `☐`) - just make sure the font you are using in your terminal supports those characters.

**Comment by Paffo** [comment]
the Powershell terminal works much faster, thanks.
In the first tab i have other than the newly implemented checkbox, some TextBoxes but i cannot select them as pressing TAB key switches tab in the TabPanel.

**Comment by TomaszRewak** [comment]
Nice!
Ah, right. then probably you will have to either go with some other key or stick with the first option.
