### ISSUE TITLE
How to add control and menu?

### ISSUE THREAD

**Issue by hubabuba444** [TomaszRewak/C-sharp-console-multiplexer#29]
English:How to add control and menu?
Polish:Jak dodać kontrolkę i menu?

**Comment by TomaszRewak** [comment]
Hey @hubabuba444 

Sorry for a late reply.

If you don't mind, I will continue the thread in English only, so that others can benefit from it as well. Though let me know if you would prefer to discuss it in Polish.

What control/menu do you have in mind? In general new controls and menus can be added to the view using the `ConsoleManager.Content` endpoint. Apart for the list of predefined controls, one can also create custom ones using the `SimpleControl` class or the `IControl` interface.

If you provide me with more information about your use case, I might be able to help you better.

**Comment by hubabuba444** [comment]
means how to show the control

**Comment by TomaszRewak** [comment]
In general, all you have to do is to assign your control to the `ConsoleManager.Content`:

```csharp
ConsoleManager.Content = new TextBlock { Text = "Hello world" };
```

You don't need to explicitly call any `Show` methods, or anything like that.
In that regard it works similarly to the WPF. The `ConsoleManager` maintains a logic tree of what your application should look like and automatically invokes redraw cycles whenever needed - based on the changes in your layout.

**Comment by hubabuba444** [comment]
OK
